################################################################################
# 환경별 설정 파일 관리를 위한 기본 설정
################################################################################

spring:
  application:
    name: codify-v1
  # 애플리케이션 실행 시 활성화될 프로필 설정
  profiles:
    # 함께 포함되어 활성화 될 공통 설정 프로필
    include:
      - common
    # 활성화 될 프로필
    active:
      - local
