###########################################################################
# 인 메모리 DB 개발 환경
###########################################################################

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  sql:
    init:
      mode: EMBEDDED
      schema-locations:
        - classpath:sql/h2/schema.sql
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  port: 80